package com.ruiyun.jvppeteer.enums;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum BrowserLanguageEnum {
    AE("ar-SA,en-US"),
    AL("en-GB"),
    AR("es-MX"),
    AT("de-DE"),
    AU("en-GB"),
    AZ("en-GB"),
    BA("hr-HR"),
    BD("en-GB"),
    // BE("fr-FR"),
    BE("nl-BE"),
    BG("en-US"),
    BH("ar-SA,en-US"),
    BN("ms-MY"),
    BO("es-MX"),
    BR("pt-BR"),
    BY("en-US"),
    BZ("en-GB"),
    CA("en-US"),
    CL("es-MX"),
    CM("fr-FR"),
    CN("zh-CN"),
    CO("es-MX"),
    CR("es-MX"),
    CZ("cs-CZ"),
    DE("de-DE"),
    DK("da-DK"),
    DO("es-MX"),
    DZ("ar-SA,en-US"),
    EC("es-MX"),
    EE("en-GB"),
    EG("ar-SA,en-US"),
    ES("eu-ES"),
    ET("am-ET"),
    FR("fr-FR"),
    GB("en-GB"),
    GR("el-GR,en-US"),
    GT("es-MX"),
    HK("zh-HK,en-GB"),
    HN("es-MX"),
    HR("en-GB"),
    HT("fr-FR"),
    HU("hu-HU"),
    ID("id-ID"),
    IE("en-GB"),
    IL("he-IL,en-US"),
    IN("hi-IN,en-IN"),
    IQ("ar-SA,en-US"),
    IR("fa-IR,en-US"),
    IS("is-IS"),
    IT("it-IT"),
    JM("en-GB"),
    JO("ar-SA,en-US"),
    JP("ja-JP"),
    KE("sw-KE"),
    KH("en-US"),
    KW("ar-SA,en-US"),
    KZ("en-US"),
    LA("en-US"),
    LB("ar-SA,en-US"),
    LI("de-DE"),
    LT("en-GB"),
    LV("en-GB"),
    MA("ar-SA,en-US"),
    MC("fr-FR"),
    MD("ro-RO"),
    ME("en-GB"),
    MX("es-MX"),
    MY("en-GB"),
    NG("ha-Latn-NG"),
    NI("es-MX"),
    NL("nl-NL"),
    NO("nb-NO"),
    NZ("en-GB"),
    OM("ar-SA,en-US"),
    PA("es-MX"),
    PE("es-MX"),
    PH("en-US"),
    PL("pl-PL"),
    PR("es-MX"),
    PT("pt-PT"),
    PY("es-MX"),
    QA("ar-SA,en-US"),
    RE("fr-FR"),
    RO("ro-RO"),
    RS("en-GB"),
    RU("ru-RU,en-US"),
    SA("ar-SA,en-US"),
    SE("sv-SE"),
    SG("zh-CN,en-GB"),
    SI("en-GB"),
    SK("sk-SK"),
    SN("fr-FR"),
    SV("es-MX"),
    SY("ar-SA,en-US"),
    TH("en-US"),
    TN("ar-SA,en-US"),
    TR("tr-TR"),
    TT("en-GB"),
    TW("zh-TW,en-US"),
    UA("en-US"),
    US("en-US"),
    UY("es-MX"),
    UZ("en-GB"),
    VN("vi-VN"),
    YE("ar-SA,en-US"),
    ZA("en-GB"),
    ZW("en-GB");

    public final String browserLanguage;

    public static BrowserLanguageEnum enumOf(String code) {
        BrowserLanguageEnum[] values = BrowserLanguageEnum.values();
        for(BrowserLanguageEnum v: values) {
            if(v.name().equalsIgnoreCase(code)) {
                return v;
            }
        }
        return null;
    }
}
